# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'panel.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(30, 20, 47, 13))
        self.label1.setObjectName("label1")
        self.label2 = QtWidgets.QLabel(self.centralwidget)
        self.label2.setGeometry(QtCore.QRect(30, 50, 47, 13))
        self.label2.setObjectName("label2")
        self.label3 = QtWidgets.QLabel(self.centralwidget)
        self.label3.setGeometry(QtCore.QRect(30, 80, 47, 13))
        self.label3.setObjectName("label3")
        self.btn3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn3.setGeometry(QtCore.QRect(420, 210, 75, 23))
        self.btn3.setObjectName("btn3")
        self.tbl1 = QtWidgets.QTableWidget(self.centralwidget)
        self.tbl1.setGeometry(QtCore.QRect(230, 20, 341, 171))
        self.tbl1.setRowCount(30)
        self.tbl1.setColumnCount(3)
        self.tbl1.setObjectName("tbl1")
        self.cmb2 = QtWidgets.QComboBox(self.centralwidget)
        self.cmb2.setGeometry(QtCore.QRect(310, 210, 101, 22))
        self.cmb2.setObjectName("cmb2")
        self.btn2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn2.setGeometry(QtCore.QRect(230, 210, 75, 23))
        self.btn2.setObjectName("btn2")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(80, 20, 135, 103))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lne1 = QtWidgets.QLineEdit(self.widget)
        self.lne1.setObjectName("lne1")
        self.verticalLayout.addWidget(self.lne1)
        self.lne2 = QtWidgets.QLineEdit(self.widget)
        self.lne2.setObjectName("lne2")
        self.verticalLayout.addWidget(self.lne2)
        self.cmb1 = QtWidgets.QComboBox(self.widget)
        self.cmb1.setObjectName("cmb1")
        self.verticalLayout.addWidget(self.cmb1)
        self.btn1 = QtWidgets.QPushButton(self.widget)
        self.btn1.setObjectName("btn1")
        self.verticalLayout.addWidget(self.btn1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label1.setText(_translate("MainWindow", "Name"))
        self.label2.setText(_translate("MainWindow", "Surname"))
        self.label3.setText(_translate("MainWindow", "Company"))
        self.btn3.setText(_translate("MainWindow", "Filter"))
        self.btn2.setText(_translate("MainWindow", "Delete"))
        self.btn1.setText(_translate("MainWindow", "Add"))
